### ISSUE TITLE
Flashing & Pinout

### ISSUE THREAD

**Issue by kub3let** [koendv/blackmagic-firmware#1]
Got my Black Pill v2 today.

Download dfu-util from https://dfu-util.sourceforge.net/

- Connect the Black Pill directly via USB C (make sure it's a data cable, not charging cable)
- Push NRST and BOOT0
- Wait a few seconds
- Release NRST
- Wait a few seconds
- Release BOOT0
- Upload the firmware: ./dfu-util -a 0 --dfuse-address 0x08000000:leave -R -D blackmagic-blackpillv2.bin

If you get the error `Cannot open DFU device xxxx:xxxx` download https://zadig.akeo.ie/, select the STM32 Bootloader and install the WinUSB driver then run dfu-util again.

Pinout:

- JTAG/SWD
  - A1: TDI
  - DIO: TMS/SWDIO
  - SCK: TCK/SWCLK
  - B3: TDO/TRACESWO
  - B5: TRST
  - B4: nRST
  
- USB / USART
  - B6: USART1 TX - connect with RX from microcontroller
  - B7: USART1 RX - connect with TX from microcontroller

**Comment by koendv** [comment]
OK, Thanks. Documentation updated.

https://github.com/koendv/blackmagic-firmware/blob/master/INSTALL.md

Hope you enjoy this little debugger.

koen

**Comment by koendv** [comment]
One thing I'd like to ask: are .inf files still relevant for Windows today?
https://github.com/blackmagic-debug/blackmagic/tree/main/driver

koen

**Comment by kub3let** [comment]
> One thing I'd like to ask: are .inf files still relevant for Windows today? https://github.com/blackmagic-debug/blackmagic/tree/main/driver koen

I did not use it and the names are all correct under device manager.

So it does not seem to be needed.
